config/routes.rb
Rails.application.routes.draw do



  # Home Principal ---------------------------
  namespace :main, path: '' do
    root to: 'home#index'
    get 'nosotros', to: 'static_pages#about', as: :about
    get 'contacto', to: 'static_pages#contact', as: :contact
  end


  post 'mercado_pago/webhook', to: 'mercado_pago_webhooks#receive'

  # E-commerce Principal -------------------------------------------------------------------------
  namespace :ecommerce, path: '' do

    # Ruta para búsqueda de productos
    get 'productos/search', to: 'products#search', as: :search_products


    # Vistas especiales
    get 'super-ofertas', to: 'products#super_offers', as: :super_offers
    get 'novedades',      to: 'products#new_arrivals', as: :new_arrivals
    get 'mas-vendidos',   to: 'products#best_sellers', as: :best_sellers
    get 'historial',      to: 'products#history', as: :history
    delete 'historial',   to: 'products#clear_history', as: :clear_history
    delete 'historial/:id', to: 'products#remove_from_history', as: :remove_from_history


    resources :categories, only: [:index, :show], path: 'categorias' do
      resources :subcategories, only: [:index, :show], path: 'subcategorias' do
        resources :products, only: [:index, :show], path: 'productos'
      end
    end

    resources :products, only: [:index, :show], path: 'productos' do
      resources :product_variants, only: [:show]
    end

    resource :cart, only: [:show], path: 'carrito' do
      delete 'vaciar', to: 'carts#clear_cart', as: :clear_cart
    end

    resources :cart_items, only: [:create, :update, :destroy], path: 'carrito/items'

    resources :orders, only: [:new, :show, :index], path: 'compras' do
      member do
        # Nuevo paso: Selección o creación de dirección de envío
        get   'informacion-envio',  to: 'orders#shipping_info',       as: :shipping_info
        patch 'informacion-envio',  to: 'orders#update_shipping_info',  as: :update_shipping_info

        # Selección del método de envío
        get   'envio',  to: 'orders#shipping',        as: :shipping
        patch 'envio',  to: 'orders#update_shipping', as: :update_shipping

        # Selección del método de pago
        get   'pago',  to: 'orders#payment',         as: :payment
        patch 'pago',  to: 'orders#update_payment',  as: :update_payment

        # Resumen de la compra
        get 'resumen', to: 'orders#summary',         as: :summary

        # Finalización de la compra
        post 'finalizar', to: 'orders#finalize',     as: :finalize

        # Cancelar la compra
        post :cancel

        # Generar PDF de la orden
        get :pdf

        # Confirmación exitosa de la compra
        get 'exito', to: 'orders#success', as: :success

        # Subir comprobante de pago
        patch :upload_comprobante
      end

    end

  end






  # modulo de administración
  namespace :admin do
    root to: 'dashboard#index'
    resources :banners
    resources :discount_ranges, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :shipping_methods, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :payment_methods, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :bank_accounts, only: [:index, :new, :create, :edit, :update, :destroy]
    resource :settings, only: [:show, :update]
    resources :mercado_pago_tokens, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :products do
      get 'load_subcategories', on: :collection
      resources :product_variants, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :categories do
      resources :subcategories, only: [:index, :new, :create, :edit, :update, :destroy]
    end



    resources :orders, only: [:index, :show, :destroy, :update] do
      collection do
        get 'home', to: 'orders#home'
        get 'pendientes', to: 'orders#pendientes'
        get 'pagos', to: 'orders#pagos'
        get 'preparacion', to: 'orders#preparacion'
        get 'finalizadas', to: 'orders#finalizadas'
      end
      member do
        patch 'cambiar_estado', to: 'orders#cambiar_estado'
        get 'print', to: 'orders#print'  # Nueva ruta para impresión
      end
    end

    resources :users do
      collection do
        get 'clientes', to: 'users#clientes'
        get 'admins', to: 'users#admins'
      end
      resources :addresses, only: [:create, :edit, :update, :destroy, :new]
    end

    namespace :users, path: 'usuarios' do
      get '/', to: 'main#index', as: :main
      resources :administradores, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
        member do
          patch :toggle_status
        end
      end
      resources :repositores, only: [:index, :show, :edit, :new, :create, :update, :destroy]
      resources :cajeros, only: [:index, :show, :edit, :new, :create, :update, :destroy]
      resources :clientes_regular, only: [:index, :show, :edit, :new, :create, :update, :destroy]
      resources :clientes_mayorista, only: [:index, :show, :edit, :new, :create, :update, :destroy]
    end

  end

  # Módulo de minoristas
  namespace :store do
    root to: 'home#index'
  end

  # Módulo de mayoristas
  namespace :business do
    # Página principal y estáticas
    root to: 'home#index'

    # Búsqueda y vistas especiales de productos
    get 'productos/search', to: 'products#search', as: :search_products
    get 'super-ofertas', to: 'products#super_offers', as: :super_offers
    get 'novedades', to: 'products#new_arrivals', as: :new_arrivals
    get 'mas-vendidos', to: 'products#best_sellers', as: :best_sellers
    get 'historial', to: 'products#history', as: :history
    delete 'historial', to: 'products#clear_history', as: :clear_history
    delete 'historial/:id', to: 'products#remove_from_history', as: :remove_from_history

    # Navegación por categorías
    resources :categories, only: [:index, :show], path: 'categorias' do
      resources :subcategories, only: [:index, :show], path: 'subcategorias' do
        resources :products, only: [:index, :show], path: 'productos'
      end
    end

    # Productos y variantes
    resources :products, only: [:index, :show], path: 'productos' do
      resources :product_variants, only: [:show]
    end

    # Carrito
    resource :cart, only: [:show], path: 'carrito' do
      delete 'vaciar', to: 'carts#clear_cart', as: :clear_cart
    end

    resources :cart_items, only: [:create, :update, :destroy], path: 'carrito/items'

    # Órdenes
    resources :orders, only: [:new, :show, :index], path: 'compras' do
      member do
        get 'informacion-envio', to: 'orders#shipping_info', as: :shipping_info
        patch 'informacion-envio', to: 'orders#update_shipping_info', as: :update_shipping_info

        get 'envio', to: 'orders#shipping', as: :shipping
        patch 'envio', to: 'orders#update_shipping', as: :update_shipping

        get 'pago', to: 'orders#payment', as: :payment
        patch 'pago', to: 'orders#update_payment', as: :update_payment

        get 'resumen', to: 'orders#summary', as: :summary
        post 'finalizar', to: 'orders#finalize', as: :finalize
        post :cancel
        get :pdf
        get 'exito', to: 'orders#success', as: :success
        patch :upload_comprobante
      end
    end

    # Cuenta del usuario
    namespace :account, path: 'mi-cuenta' do
      get '/', to: 'main#show', as: :main

      resource :profile, only: [:show, :update], path: 'perfil' do
        get 'informacion', on: :collection
        get 'editar-nombre', to: 'profiles#edit_name', as: :edit_name
        get 'editar-telefono', to: 'profiles#edit_phone', as: :edit_phone
        get 'editar-dni', to: 'profiles#edit_dni', as: :edit_dni
        patch 'foto', to: 'profiles#update_profile_picture', as: :update_picture

        get 'verificacion-fiscal', to: 'profiles#fiscal_verification_form', as: :fiscal_verification_form
        patch 'constancia-fiscal', to: 'profiles#upload_constancia_fiscal', as: :upload_constancia_fiscal
        get 'verificacion-en-proceso', to: 'profiles#fiscal_verification_pending', as: :fiscal_verification_pending
      end

      resources :lists, only: [:index, :show, :new, :create, :destroy], path: 'listas' do
        resources :list_items, only: [:create, :destroy], path: 'productos'
      end

      resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy, :show], path: 'direcciones' do
        member do
          patch :set_default
        end
      end

      resources :transporte_preferidos, only: [:index, :new, :create, :edit, :update, :destroy], path: 'transportes-preferidos' do
        member do
          patch :set_default
        end
      end


      resources :orders, only: [:index, :show], path: 'compras'
      resource :facturacion, only: [:show], path: 'facturacion'


      resource :settings, only: [:show], path: 'configuracion' do
        delete 'eliminar-cuenta', on: :collection, to: 'settings#delete_account', as: :delete_account

        get 'editar-contrasena', to: 'settings#edit_password', as: :edit_password
        patch 'actualizar-contrasena', to: 'settings#update_password', as: :update_password

        get 'editar-email', to: 'settings#edit_email', as: :edit_email
        patch 'actualizar-email', to: 'settings#update_email', as: :update_email
      end

    end

    # Centro de ayuda
    namespace :help, path: 'ayuda' do
      get '/', to: 'static_pages#index', as: :index
      get 'nosotros', to: 'static_pages#about', as: :about
      get 'contacto', to: 'static_pages#contact', as: :contact
      get 'constancia-arca', to: 'static_pages#constancia_arca', as: :constancia_arca
      # Más artículos en el futuro:
      # get 'como-comprar', to: 'static_pages#how_to_buy', as: :how_to_buy
    end



  end

  # Módulo de punto de venta (POS)
  namespace :pos do
    root to: 'home#index'
  end

  # Módulo de logística
  namespace :logistics do
    root to: 'home#index'
  end

app/controllers/account/accounts_controller.rb
class Account::AccountsController < ApplicationController
  before_action :authenticate_user!

  def main
    @user = current_user
  end
end

app/controllers/account/addresses_controller.rb
class Account::AddressesController < ApplicationController
  before_action :authenticate_user!

  def index
    @addresses = current_user.addresses.order(created_at: :desc)
  end

  def show
    @address = current_user.addresses.find(params[:id])
  end


  def new
    @address = current_user.addresses.new
  end

  def create
    @address = current_user.addresses.new(address_params)
    if @address.save
      redirect_to account_addresses_path, notice: 'Dirección agregada con éxito.'
    else
      render :new
    end
  end

  def edit
    @address = current_user.addresses.find(params[:id])
  end

  def update
    @address = current_user.addresses.find(params[:id])
    if @address.update(address_params)
      redirect_to account_addresses_path, notice: 'Dirección actualizada con éxito.'
    else
      render :edit
    end
  end

  def destroy
    @address = current_user.addresses.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to account_addresses_path, notice: 'Dirección eliminada con éxito.' }
      format.turbo_stream
    end
  end

  private

  def address_params
    params.require(:address).permit(
      :street_name,
      :street_number,
      :floor,
      :apartment,
      :locality,
      :city,
      :province_code,
      :postal_code,
      :indications
    )
  end

end

app/controllers/account/profiles_controller.rb
class Account::ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :update, :update_profile_picture]

  def show
    # Vista del perfil del usuario
  end

  def information
    # Vista de información personal
  end

  def edit_name
    # Formulario para editar nombre
  end

  def edit_email
    # Formulario para editar email
  end

  def edit_phone
    # Formulario para editar teléfono
  end

  def edit_dni
    @user = current_user
  end


  def update
    if @user.update(user_params)
      redirect_to information_account_profiles_path(@user), notice: 'Perfil actualizado exitosamente.'
    else
      flash.now[:alert] = 'Hubo un problema al actualizar el perfil.'
      render :edit_name  # Renderiza la vista de edición con errores
    end
  end

  def update_profile_picture
    if params[:user][:profile_picture].present?
      processed_image = ImageProcessing::MiniMagick
                          .source(params[:user][:profile_picture])
                          .resize_to_limit(600, 600)
                          .convert("webp")
                          .call

      @user.profile_picture.purge if @user.profile_picture.attached?
      @user.profile_picture.attach(
        io: processed_image,
        filename: "profile_picture_#{@user.id}.webp",
        content_type: "image/webp"
      )

      redirect_to account_profile_path(@user), notice: 'Foto de perfil actualizada exitosamente.'
    else
      redirect_to account_profile_path(@user), alert: "Debés seleccionar una imagen."
    end
  end


  private

  def set_user
    @user = current_user
  end

  def profile_picture_params
    params.require(:user).permit(:profile_picture)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, :document_type, :document_id)
  end

end

app/controllers/account/settings_controller.rb
class Account::SettingsController < ApplicationController
  before_action :authenticate_user!

  def show
    # Vista de ajustes
  end

  def delete_account
    # current_user.purchases.destroy_all    # Elimina todas las compras del usuario
    current_user.destroy
    redirect_to root_path, notice: 'Tu cuenta ha sido eliminada.'
  end
end

app/controllers/business/account/addresses_controller.rb
module Business
  module Account
    class AddressesController < ApplicationController
      before_action :set_envio_address, only: [:edit, :update, :destroy]

      def index
        @envio_addresses = current_user.addresses.direccion_envio.order(created_at: :desc)
      end

      def new
        @envio_address = current_user.addresses.new(address_type: :direccion_envio)
      end

      def create
        @envio_address = current_user.addresses.new(address_params)
        @envio_address.address_type = :direccion_envio

        # Si no se marcó como default y no hay ninguna dirección predeterminada aún
        if !@envio_address.default_shipping && current_user.addresses.where(default_shipping: true).empty?
          @envio_address.default_shipping = true
        end

        if @envio_address.save
          redirect_to business_account_addresses_path, notice: 'Dirección creada correctamente.'
        else
          render :new, status: :unprocessable_entity
        end
      end

      def edit
      end

      def set_default
        current_user.addresses.update_all(default_shipping: false)
        address = current_user.addresses.find(params[:id])
        address.update(default_shipping: true)
        redirect_to business_account_addresses_path, notice: "Dirección principal actualizada."
      end

      def update
        if @envio_address.update(address_params)
          redirect_to business_account_addresses_path, notice: 'Dirección actualizada correctamente.'
        else
          render :edit, status: :unprocessable_entity
        end
      end

      def destroy
        was_default = @envio_address.default_shipping
        @envio_address.destroy

        if was_default
          next_default = current_user.addresses.order(created_at: :asc).first
          next_default.update(default_shipping: true) if next_default.present?
        end

        redirect_to business_account_addresses_path, notice: 'Dirección eliminada correctamente.'
      end

      private

      def set_envio_address
        @envio_address = current_user.addresses.direccion_envio.find(params[:id])
      end

      def address_params
        params.require(:address).permit(
          :street_name,
          :street_number,
          :floor,
          :apartment,
          :locality,
          :city,
          :province_code,
          :postal_code,
          :indications,
          :default_shipping
        )
      end
    end
  end
end

app/controllers/business/account/facturacions_controller.rb
module Business
  module Account
    class FacturacionsController < ApplicationController
      before_action :authenticate_user!

      def show
        @user = current_user
        @fiscal_address = @user.addresses.direccion_fiscal.first
      end
    end
  end
end

app/controllers/business/account/list_items_controller.rb
module Business
  module Account
    class ListItemsController < ApplicationController
      before_action :authenticate_user!
      before_action :set_list

      def create
        @list_item = @list.list_items.new(product_id: params[:product_id])
        if @list_item.save
          redirect_to business_account_list_path(@list), notice: 'Producto agregado a la lista'
        else
          redirect_back fallback_location: business_account_list_path(@list), alert: 'Ya estaba en la lista'
        end
      end

      def destroy
        @list_item = @list.list_items.find(params[:id])
        @list_item.destroy
        redirect_to business_account_list_path(@list), notice: 'Producto eliminado de la lista'
      end

      private

      def set_list
        @list = current_user.lists.find(params[:list_id])
      end
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/business/account/profiles/fiscal_verification_pending.html.erb
<section class="account-business-fiscal-verification-pending">
  <div class="fiscal-verification-pending-container">

    <svg class="icon">
      <use xlink:href="<%= asset_path('icons/business.svg#Icono-verificacion-fiscal') %>"></use>
    </svg>
    <h1 class="title">
      Estamos verificando tus datos
    </h1>
    <p class="description">
      Tu constancia está siendo verificada. En un plazo de 24 horas te avisaremos si fue aprobada. Mientras tanto, podés seguir usando tu cuenta con total normalidad.
    </p>
    <div class="actions">
      <%= link_to 'Ir al inicio', business_root_path, class: 'btn btn-primary' %>
      <%= link_to 'Volver', informacion_business_account_profile_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</section>

app/views/business/account/profiles/informacion.html.erb
<% content_for :title, "Información Personal" %>



<div class="account-business-informacion">
  <section class="sidebar-accounts-business">
    <div class="sidebar-section">

      <%= link_to business_account_main_path, class: 'link' do %>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-home-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Mi cuenta</h2>
      <% end %>

      <%= link_to business_account_orders_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-compras-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Compras</h2>
      <% end %>

      <%= link_to business_account_profile_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-user-account-2') %>"></use>
        </svg>
        <h2 class="select-view">Mi perfil</h2>
      <% end %>

      <%= link_to business_account_lists_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-listas-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Mis listas</h2>
      <% end %>

      <%= link_to business_account_facturacion_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-facturacion-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Facturación</h2>
      <% end %>

      <%= link_to business_account_settings_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-ajustes-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Ajustes</h2>
      <% end %>

    </div>
  </section>

  <section class="account-business-content">
    <div class="profile-info-business">
      <div class="profile-info-container">


        <div class="products-navigation">
          <ol>
            <li>
              <%= link_to business_account_profile_path do %>
                <span>Mi perfil</span>
                <svg class="icon">
                  <use xlink:href="<%= asset_path('icons/business.svg#flecha-separacion-siguiente') %>"></use>
                </svg>
              <% end %>
            </li>

            <li>
              <span>Información Personal</span>
            </li>

          </ol>
        </div>

        <div class="categories-title">
          <div class="title">
            <%= link_to business_account_profile_path, class: 'arrow-back-link' do %>
              <svg class="icon">
                <use xlink:href="<%= asset_path('icons/business.svg#icon-arrow') %>"></use>
              </svg>
            <% end %>
            <h1 class="category-title">Administrá tu información</h1>
          </div>
        </div>

        <div class="profile-personal-info">

          <div class="profile-info-item profile-name-info">
            <div class="profile-info-detail">
              <h4 class="profile-info-label">Nombre elegido</h4>
              <p class="profile-info-value"><%= "#{current_user.first_name} #{current_user.last_name}" %></p>
            </div>
            <%= link_to 'Modificar', edit_name_business_account_profile_path, class: 'profile-info-edit-link' %>
          </div>

          <% if current_user.razon_social.present? %>
            <div class="profile-info-item profile-name-info">
              <div class="profile-info-detail">
                <h4 class="profile-info-label">Razón social</h4>
                <p class="profile-info-value"><%= current_user.razon_social %></p>
              </div>
              <%= link_to 'Modificar', '#', class: 'profile-info-edit-link disabled-link', tabindex: -1, aria_disabled: true %>
            </div>
          <% end %>

          <div class="profile-info-item profile-name-info">
            <div class="profile-info-detail">
              <h4 class="profile-info-label">Condición fiscal</h4>
              <p class="profile-info-value"><%= current_user.condicion_fiscal.humanize %></p>
            </div>
            <%= link_to 'Modificar', fiscal_verification_form_business_account_profile_path, class: 'profile-info-edit-link' %>
          </div>

          <div class="profile-info-item profile-telephone-info">
            <div class="profile-info-detail">
              <h4 class="profile-info-label">Teléfono</h4>
              <p class="profile-info-value">
                <%= current_user.phone.present? ? current_user.phone : "<span class='missing-data'>Actualiza tu teléfono</span>".html_safe %>
              </p>
            </div>
            <%= link_to 'Modificar', edit_phone_business_account_profile_path, class: 'profile-info-edit-link' %>
          </div>

          <div class="profile-info-item profile-dni-info">
            <div class="profile-info-detail">
              <h4 class="profile-info-label">Tu número de <%= current_user.document_type %></h4>
              <p class="profile-info-value">
                <% case current_user.document_type.to_sym %>
                <% when :CUIL, :CUIT %>
                  <%= current_user.document_id&.gsub(/(\d{2})(\d{8})(\d{1})/, '\1-\2-\3') %>
                <% else %>
                  <%= current_user.document_id %>
                <% end %>
              </p>
            </div>
            <%= link_to 'Modificar', edit_dni_business_account_profile_path, class: 'profile-info-edit-link' %>
          </div>
        </div>
        
      </div>
    </div>
  </section>

</div>

<%= render 'business/shared/footer_business' %>

app/views/business/account/profiles/show.html.erb
<% content_for :title, "Mi perfil" %>

<div class="account-business-profiles">
  <section class="sidebar-accounts-business">
    <div class="sidebar-section">

      <%= link_to business_account_main_path, class: 'link' do %>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-home-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Mi cuenta</h2>
      <% end %>

      <%= link_to business_account_orders_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-compras-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Compras</h2>
      <% end %>

      <%= link_to business_account_profile_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-user-account-2') %>"></use>
        </svg>
        <h2 class="select-view">Mi perfil</h2>
      <% end %>

      <%= link_to business_account_lists_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-listas-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Mis listas</h2>
      <% end %>

      <%= link_to business_account_facturacion_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-facturacion-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Facturación</h2>
      <% end %>

      <%= link_to business_account_settings_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-ajustes-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Ajustes</h2>
      <% end %>

    </div>
  </section>

  <section class="account-business-content">
    <div class="profile-show-business">

      <div class="categories-title-business">
        <div class="title">
          <%= link_to business_account_main_path, class: 'arrow-back-link' do %>
            <svg class="icon">
              <use xlink:href="<%= asset_path('icons/admin.svg#icon-arrow') %>"></use>
            </svg>
          <% end %>
          <h1 class="category-title">Mi perfil</h1>
          <div class="arrow-back-link space"></div>
        </div>
      </div>

      <div class="profile-container">
        <div class="profile-pictures">

          <%= form_with model: @user, url: update_picture_business_account_profile_path, method: :patch, local: true, html: { class: "profile-form", data: { controller: "avatar-profiles" } } do |f| %>

            <div class="field profile-picture-field">
              <%= f.file_field :profile_picture, accept: "image/*", data: { action: "change->avatar-profiles#preview", avatar_profiles_target: "input" }, class: 'profile-file-input', style: "display: none;" %>
              <div class="profile-picture-preview" data-action="click->avatar-profiles#selectFile">
                <% if @user.profile_picture.attached? %>
                  <%= image_tag url_for(@user.profile_picture), id: "profilePreview", alt: "Vista previa de la foto de perfil", class: "preview-image" %>
                <% else %>
                  <div class="no-image-preview">
                    <p class="no-image-text"><%= "#{@user.first_name.first}#{@user.last_name.first}".upcase %></p>
                  </div>
                <% end %>
              </div>
              <svg class="icon-camera">
                <use xlink:href="<%= asset_path('icons/business.svg#icon-camera-account') %>"></use>
              </svg>
            </div>
          <% end %>

          <div class="user-info">
            <p class="user-name"><%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></p>
            <p class="user-email"><%= @user.email %></p>
            <p class="user-status"><%= @user.role.humanize %></p>
          </div>
        </div>

        <div class="profile-links">
          <%= link_to informacion_business_account_profile_path, class: 'profile-link' do %>
            <svg class="icon-3d">
              <use xlink:href="<%= asset_path('icons/business.svg#icon-user-3d') %>"></use>
            </svg>
            <div class="link-content">
              <h2 class="link-title">Información Personal</h2>
              <p class="link-description">Información de tu documento de identidad y actividad fiscal.</p>
            </div>
            <svg class="icon-end">
              <use xlink:href="<%= asset_path('icons/business.svg#Icon-arrrow-rigt') %>"></use>
            </svg>
          <% end %>

          <%= link_to business_account_addresses_path, class: 'profile-link' do %>
            <svg class="icon-3d">
              <use xlink:href="<%= asset_path('icons/business.svg#icon-direccion-3d') %>"></use>
            </svg>
            <div class="link-content">
              <h2 class="link-title">Mis Direcciones</h2>
              <p class="link-description">Consulta y actualiza tus direcciones</p>
            </div>
            <svg class="icon-end">
              <use xlink:href="<%= asset_path('icons/business.svg#Icon-arrrow-rigt') %>"></use>
            </svg>
          <% end %>

          <%= link_to business_account_transporte_preferidos_path, class: 'profile-link' do %>
            <svg class="icon-3d">
              <use xlink:href="<%= asset_path('icons/business.svg#icon-transportes-3d') %>"></use>
            </svg>
            <div class="link-content">
              <h2 class="link-title">Mis servicios de envíos</h2>
              <p class="link-description">Transportistas preferidos guardados en mi cuenta.</p>
            </div>
            <svg class="icon-end">
              <use xlink:href="<%= asset_path('icons/business.svg#Icon-arrrow-rigt') %>"></use>
            </svg>
          <% end %>

        </div>
      </div>
      
    </div>
  </section>

</div>

<%= render 'business/shared/footer_business' %>