config/routes.rb
Rails.application.routes.draw do



  # Home Principal ---------------------------
  namespace :main, path: '' do
    root to: 'home#index'
    get 'nosotros', to: 'static_pages#about', as: :about
    get 'contacto', to: 'static_pages#contact', as: :contact
  end


  post 'mercado_pago/webhook', to: 'mercado_pago_webhooks#receive'

  # E-commerce Principal -------------------------------------------------------------------------
  namespace :ecommerce, path: '' do

    # Ruta para búsqueda de productos
    get 'productos/search', to: 'products#search', as: :search_products


    # Vistas especiales
    get 'super-ofertas', to: 'products#super_offers', as: :super_offers
    get 'novedades',      to: 'products#new_arrivals', as: :new_arrivals
    get 'mas-vendidos',   to: 'products#best_sellers', as: :best_sellers
    get 'historial',      to: 'products#history', as: :history
    delete 'historial',   to: 'products#clear_history', as: :clear_history
    delete 'historial/:id', to: 'products#remove_from_history', as: :remove_from_history


    resources :categories, only: [:index, :show], path: 'categorias' do
      resources :subcategories, only: [:index, :show], path: 'subcategorias' do
        resources :products, only: [:index, :show], path: 'productos'
      end
    end

    resources :products, only: [:index, :show], path: 'productos' do
      resources :product_variants, only: [:show]
    end

    resource :cart, only: [:show], path: 'carrito' do
      delete 'vaciar', to: 'carts#clear_cart', as: :clear_cart
    end

    resources :cart_items, only: [:create, :update, :destroy], path: 'carrito/items'

    resources :orders, only: [:new, :show, :index], path: 'compras' do
      member do
        # Nuevo paso: Selección o creación de dirección de envío
        get   'informacion-envio',  to: 'orders#shipping_info',       as: :shipping_info
        patch 'informacion-envio',  to: 'orders#update_shipping_info',  as: :update_shipping_info

        # Selección del método de envío
        get   'envio',  to: 'orders#shipping',        as: :shipping
        patch 'envio',  to: 'orders#update_shipping', as: :update_shipping

        # Selección del método de pago
        get   'pago',  to: 'orders#payment',         as: :payment
        patch 'pago',  to: 'orders#update_payment',  as: :update_payment

        # Resumen de la compra
        get 'resumen', to: 'orders#summary',         as: :summary

        # Finalización de la compra
        post 'finalizar', to: 'orders#finalize',     as: :finalize

        # Cancelar la compra
        post :cancel

        # Generar PDF de la orden
        get :pdf

        # Confirmación exitosa de la compra
        get 'exito', to: 'orders#success', as: :success

        # Subir comprobante de pago
        patch :upload_comprobante
      end

    end

  end






  # modulo de administración
  namespace :admin do
    root to: 'dashboard#index'
    resources :banners
    resources :discount_ranges, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :shipping_methods, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :payment_methods, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :bank_accounts, only: [:index, :new, :create, :edit, :update, :destroy]
    resource :settings, only: [:show, :update]
    resources :mercado_pago_tokens, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :products do
      get 'load_subcategories', on: :collection
      resources :product_variants, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :categories do
      resources :subcategories, only: [:index, :new, :create, :edit, :update, :destroy]
    end



    resources :orders, only: [:index, :show, :destroy, :update] do
      collection do
        get 'home', to: 'orders#home'
        get 'pendientes', to: 'orders#pendientes'
        get 'pagos', to: 'orders#pagos'
        get 'preparacion', to: 'orders#preparacion'
        get 'finalizadas', to: 'orders#finalizadas'
      end
      member do
        patch 'cambiar_estado', to: 'orders#cambiar_estado'
        get 'print', to: 'orders#print'  # Nueva ruta para impresión
      end
    end

    resources :users do
      collection do
        get 'clientes', to: 'users#clientes'
        get 'admins', to: 'users#admins'
      end
      resources :addresses, only: [:create, :edit, :update, :destroy, :new]
    end

    namespace :users, path: 'usuarios' do
      get '/', to: 'main#index', as: :main
      resources :administradores, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
        member do
          patch :toggle_status
        end
      end
      resources :repositores, only: [:index, :show, :edit, :new, :create, :update, :destroy]
      resources :cajeros, only: [:index, :show, :edit, :new, :create, :update, :destroy]
      resources :clientes_regular, only: [:index, :show, :edit, :new, :create, :update, :destroy]
      resources :clientes_mayorista, only: [:index, :show, :edit, :new, :create, :update, :destroy]
    end

  end

  # Módulo de minoristas
  namespace :store do
    root to: 'home#index'
  end

  # Módulo de mayoristas
  namespace :business do
    # Página principal y estáticas
    root to: 'home#index'

    # Búsqueda y vistas especiales de productos
    get 'productos/search', to: 'products#search', as: :search_products
    get 'super-ofertas', to: 'products#super_offers', as: :super_offers
    get 'novedades', to: 'products#new_arrivals', as: :new_arrivals
    get 'mas-vendidos', to: 'products#best_sellers', as: :best_sellers
    get 'historial', to: 'products#history', as: :history
    delete 'historial', to: 'products#clear_history', as: :clear_history
    delete 'historial/:id', to: 'products#remove_from_history', as: :remove_from_history

    # Navegación por categorías
    resources :categories, only: [:index, :show], path: 'categorias' do
      resources :subcategories, only: [:index, :show], path: 'subcategorias' do
        resources :products, only: [:index, :show], path: 'productos'
      end
    end

    # Productos y variantes
    resources :products, only: [:index, :show], path: 'productos' do
      resources :product_variants, only: [:show]
    end

    # Carrito
    resource :cart, only: [:show], path: 'carrito' do
      delete 'vaciar', to: 'carts#clear_cart', as: :clear_cart
    end

    resources :cart_items, only: [:create, :update, :destroy], path: 'carrito/items'

    # Órdenes
    resources :orders, only: [:new, :show, :index], path: 'compras' do
      member do
        get 'informacion-envio', to: 'orders#shipping_info', as: :shipping_info
        patch 'informacion-envio', to: 'orders#update_shipping_info', as: :update_shipping_info

        get 'envio', to: 'orders#shipping', as: :shipping
        patch 'envio', to: 'orders#update_shipping', as: :update_shipping

        get 'pago', to: 'orders#payment', as: :payment
        patch 'pago', to: 'orders#update_payment', as: :update_payment

        get 'resumen', to: 'orders#summary', as: :summary
        post 'finalizar', to: 'orders#finalize', as: :finalize
        post :cancel
        get :pdf
        get 'exito', to: 'orders#success', as: :success
        patch :upload_comprobante
      end
    end

    # Cuenta del usuario
    namespace :account, path: 'mi-cuenta' do
      get '/', to: 'main#show', as: :main

      resource :profile, only: [:show, :update], path: 'perfil' do
        get 'informacion', on: :collection
        get 'editar-nombre', to: 'profiles#edit_name', as: :edit_name
        get 'editar-telefono', to: 'profiles#edit_phone', as: :edit_phone
        get 'editar-dni', to: 'profiles#edit_dni', as: :edit_dni
        patch 'foto', to: 'profiles#update_profile_picture', as: :update_picture

        get 'verificacion-fiscal', to: 'profiles#fiscal_verification_form', as: :fiscal_verification_form
        patch 'constancia-fiscal', to: 'profiles#upload_constancia_fiscal', as: :upload_constancia_fiscal
        get 'verificacion-en-proceso', to: 'profiles#fiscal_verification_pending', as: :fiscal_verification_pending
      end

      resources :lists, only: [:index, :show, :new, :create, :destroy], path: 'listas' do
        resources :list_items, only: [:create, :destroy], path: 'productos'
      end

      resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy, :show], path: 'direcciones' do
        member do
          patch :set_default
        end
      end

      resources :transporte_preferidos, only: [:index, :new, :create, :edit, :update, :destroy], path: 'transportes-preferidos' do
        member do
          patch :set_default
        end
      end


      resources :orders, only: [:index, :show], path: 'compras'
      resource :facturacion, only: [:show], path: 'facturacion'


      resource :settings, only: [:show], path: 'configuracion' do
        delete 'eliminar-cuenta', on: :collection, to: 'settings#delete_account', as: :delete_account

        get 'editar-contrasena', to: 'settings#edit_password', as: :edit_password
        patch 'actualizar-contrasena', to: 'settings#update_password', as: :update_password

        get 'editar-email', to: 'settings#edit_email', as: :edit_email
        patch 'actualizar-email', to: 'settings#update_email', as: :update_email
      end

    end

    # Centro de ayuda
    namespace :help, path: 'ayuda' do
      get '/', to: 'static_pages#index', as: :index
      get 'nosotros', to: 'static_pages#about', as: :about
      get 'contacto', to: 'static_pages#contact', as: :contact
      get 'constancia-arca', to: 'static_pages#constancia_arca', as: :constancia_arca
      # Más artículos en el futuro:
      # get 'como-comprar', to: 'static_pages#how_to_buy', as: :how_to_buy
    end



  end

  # Módulo de punto de venta (POS)
  namespace :pos do
    root to: 'home#index'
  end

  # Módulo de logística
  namespace :logistics do
    root to: 'home#index'
  end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_order, only: [:show, :update, :destroy, :cambiar_estado]
    before_action :set_orders_count, only: [:home, :pendientes, :pagos, :preparacion, :finalizadas]
    before_action :set_navbar_title

    def home
      @recent_orders = Order.order(created_at: :desc).limit(10) # Últimas 10 órdenes
      @recent_payments = Order.where(status: [1, 2]).order(updated_at: :desc).limit(5) # Últimos pagos
      @recent_preparations = Order.where(status: 3).order(updated_at: :desc).limit(5) # Últimas en preparación
    end

    def pendientes
      @orders = if params[:query_text].present?
                  Order.where(status: 0).search_full_text(params[:query_text])
                else
                  Order.where(status: 0).order(created_at: :desc)
                end.page(params[:page]).per(20) # Paginación con 20 órdenes por página
      @pendientes_count = @orders.total_count # Para contar todas las órdenes sin afectar la paginación
    end

    def pagos
      @orders = if params[:query_text].present?
                  Order.where(status: [1, 2]).search_full_text(params[:query_text])
                else
                  Order.where(status: [1, 2]).order(created_at: :desc)
                end
      @pagos_count = @orders.count
    end

    def preparacion
      @orders = if params[:query_text].present?
                  Order.where(status: [3, 4, 5]).search_full_text(params[:query_text])
                else
                  Order.where(status: [3, 4, 5]).order(created_at: :desc)
                end
      @preparacion_count = @orders.count
    end

    def finalizadas
      @orders = if params[:query_text].present?
                  Order.where(status: [6, 7]).search_full_text(params[:query_text])
                else
                  Order.where(status: [6, 7]).order(created_at: :desc)
                end.page(params[:page]).per(20) # Paginación con 12 órdenes por página
      @finalizadas_count = @orders.total_count # Para contar todas las órdenes sin afectar la paginación
    end

    def cambiar_estado
      if Order.statuses.key?(params[:status])
        @order.update(status: params[:status])
        redirect_back fallback_location: admin_orders_path, notice: "Estado actualizado."
      else
        redirect_back fallback_location: admin_orders_path, alert: "Estado no válido."
      end
    end


    def show
    # Cargar datos relacionados
    @user = @order.user
    @address = @order.address
    @order_items = @order.order_items.includes(:product, :product_variant)
    @payment_method = @order.payment_method
    @shipping_method = @order.shipping_method
    end

    def destroy
      if @order.pendiente?
        @order.destroy
        redirect_to pendientes_admin_orders_path, notice: "Orden eliminada."
      else
        redirect_to admin_order_path(@order), alert: "No se puede eliminar la orden."
      end
    end


    def update
      if @order.update(order_params)
        redirect_to admin_order_path(@order), notice: "Orden actualizada correctamente."
      else
        render :show, status: :unprocessable_entity
      end
    end

    def print
      @order = Order.find(params[:id])  # Encuentra la orden por ID
      @order_items = @order.order_items.includes(:product, :variant)  # Carga los ítems de la orden
      render layout: false  # No cargar el layout normal, solo el contenido de la vista de impresión
    end


    private

    def set_navbar_title
      @navbar_title = case action_name
                      when 'home' then "Panel de Órdenes"
                      when 'pendientes' then "Órdenes en Curso"
                      when 'pagos' then "Órdenes recientes"
                      when 'preparacion' then "Órdenes en Preparación"
                      when 'finalizadas' then "Órdenes Finalizadas"
                      when 'show' then "Detalle de la Orden"
                      else "Administración de Órdenes"
                      end
    end

    def set_order
      @order = Order.find(params[:id])
    end

    def set_orders_count
      @pendientes_count = Order.where(status: 0).count
      @pagos_count = Order.where(status: [1, 2]).count
      @preparacion_count = Order.where(status: 3).count
      @finalizadas_count = Order.where(status: [6, 7]).count
    end

    def order_params
      params.require(:order).permit(:status, :other_attributes_here)
    end
  end
end

app/controllers/business/account/orders_controller.rb
module Business
  module Account
    class OrdersController < ApplicationController
      before_action :authenticate_user!

      def index
        @orders = current_user.orders.order(created_at: :desc).page(params[:page]).per(10)
      end

      def show
        @order = current_user.orders.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to business_account_orders_path, alert: 'Compra no encontrada.'
      end
    end
  end
end

app/controllers/business/orders_controller.rb
# app/controllers/business/orders_controller.rb
module Business
  class OrdersController < ApplicationController
    def new
    end

    def show
    end

    def index
    end

    def shipping_info
    end

    def update_shipping_info
    end

    def shipping
    end

    def update_shipping
    end

    def payment
    end

    def update_payment
    end

    def summary
    end

    def finalize
    end

    def cancel
    end

    def pdf
    end

    def success
    end

    def upload_comprobante
    end
  end
end

app/controllers/ecommerce/carts_controller.rb
module Ecommerce
  class CartsController < ApplicationController
    before_action :authenticate_user!

    # GET /carrito
    def show
      @cart = current_user.cart || current_user.create_cart
      @cart_items = @cart.cart_items.includes(product: :product_variants).order(id: :desc)
      @total_items = @cart.total_items

      # Obtenemos los detalles del precio del carrito
      total_info = @cart.total_price
      @subtotal = total_info[:subtotal] || 0.0
      @total_price = total_info[:subtotal_with_discount] || 0.0
      @discount_percentage = total_info[:discount_percentage] || 0.0
      @discount_amount = @subtotal - @total_price
    end

    # Vaciar carrito
    def clear_cart
      current_user.cart.cart_items.destroy_all
      redirect_to ecommerce_cart_path, notice: 'El carrito ha sido vaciado exitosamente.'
    end
  end
end

app/helpers/ecommerce/carts_helper.rb
module Ecommerce::CartsHelper
end

app/helpers/ecommerce/categories_helper.rb
module Ecommerce::CategoriesHelper
end

app/helpers/ecommerce/orders_helper.rb
module Ecommerce::OrdersHelper
end

app/helpers/ecommerce/products_helper.rb
module Ecommerce::ProductsHelper
  def time_ago_in_days(datetime)
    days_ago = (Date.today - datetime.to_date).to_i

    case days_ago
    when 0
      I18n.t('datetime.distance_in_words.today')
    when 1
      I18n.t('datetime.distance_in_words.yesterday')
    else
      I18n.t('datetime.distance_in_words.x_days', count: days_ago)
    end
  end
end

app/helpers/ecommerce/subcategories_helper.rb
module Ecommerce::SubcategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def status_class(status)
    case status
    when "pendiente"
      "status-pending"
    when "pago_pendiente"
      "status-payment-pending"
    when "pagado"
      "status-paid"
    when "en_preparacion"
      "status-in-preparation"
    when "listo_para_retirar"
      "status-ready-for-pickup"
    when "enviado"
      "status-shipped"
    when "entregado"
      "status-delivered"
    when "cancelado"
      "status-canceled"
    else
      "status-unknown"
    end
  end
end

app/views/ecommerce/orders/_navbar.html.erb
<header class="header-order">
  <nav class="header-nav">
    <div class="header-menu-logo">

      <div class="header-logo">
        <%= link_to image_tag('logos/logo.png', alt: 'Logo de [Nombre de la Tienda]'), root_path %>
      </div>

      <svg class="icon">
        <use xlink:href="<%= asset_path('icons/admin.svg#icon-lock') %>"></use>
      </svg>

    </div>
  </nav>
</header>

app/views/ecommerce/orders/index.html.erb
<% content_for :title, "Mis compras | Baratísimo Bazar" %>


<div class="purchase-history">
  <div class="purchase-history-container">

    <div class="products-navigation">
      <ol>
        <li>
          <%= link_to account_main_path do %>
            <span class="cuenta">Mi Cuenta</span>
            <svg class="icon">
              <use xlink:href="<%= asset_path('icons/ecommerce.svg#chevron') %>"></use>
            </svg>
          <% end %>
        </li>

        <li>
          <span>Mis compras</span>
        </li>

      </ol>
    </div>

    <div class="arrow-back">
      <div class="header-order-index">
        <h3 class="purchase-history-title">
          Compras
        </h3>
        <div class="barra">
        </div>
        <span class="order-count">
          <%= @orders.count %> compras
        </span>
      </div>

      <div class="search-container" data-controller="search">
        <%= form_with url: ecommerce_orders_path, method: :get, data: { controller: 'search' } do |form| %>

          <!-- Icono de búsqueda (no cambia) -->
          <svg class="icon">
            <use xlink:href="<%= asset_path('icons/admin.svg#icon-search-button') %>"></use>
          </svg>

          <div class="search-input-container">
            <%= form.text_field :query_texto, placeholder: "Nº de compra...", value: params[:query_texto], class: 'search-input', data: { search_target: 'input', action: 'input->search#toggleClearButton' } %>
          </div>

          <button type="button" id="clear-search" class="clear-button" style="display: none;" data-action="click->search#clearSearch" data-search-target="clearButton">
            <svg class="icon">
              <use xlink:href="<%= asset_path('icons/admin.svg#icon-clear') %>"></use>
            </svg>
          </button>

          <%= form.submit "Buscar", data: { action: "submit->search#submitForm" } %>
        <% end %>
      </div>
    </div>




  <div class="main-container-orders">
    <% if @orders.any? %>
      <% @orders.each do |order| %>
        <div class="order-item-card">
          <div class="order-item-header">
          <span class="header-card fecha">
            <%= I18n.l(order.created_at, format: "%d de %B %H:%M").downcase %>
          </span>
            <span class="header-card id"># <%= order.id %></span>
          </div>

          <div class="order-item-body">
            <div class="order-item-info">
              <div class="img-container-order">

                <% items_count = order.order_items.first(3).size %>
                <div class="order-images images-<%= items_count %>">
                  <% order.order_items.first(3).each do |item| %>
                    <div class="img-product-order">
                      <% if item.images.attached? %>
                        <%= image_tag url_for(item.images.first), alt: item.product.product_name, class: "product-thumbnail" %>
                      <% else %>
                        <div class="no-image">Sin imagen</div>
                      <% end %>
                    </div>
                  <% end %>
                  <% if items_count > 1 %>
                    <div class="product-info">
                      <span class="summary-label"><%= order.order_items.sum(:quantity) %></span>
                    </div>
                  <% end %>
                </div>
              </div>
              <div class="order-item-status">
                <span class="status <%= status_class(order.status) %>">
                  <%= order.status.humanize %>
                </span>

                <% case order.status %>
                  <% when "pendiente" %>
                    <span class="user-name">Aún no has finalizado tu compra.</span>
                  <% when "pago_pendiente" %>
                    <span class="user-name">Paga ahora para asegurar tu stock.</span>
                  <% when "pagado" %>
                    <span class="user-name">Tu pago ha sido confirmado con éxito.</span>
                  <% when "en_preparacion" %>
                    <span class="user-name">Tu compra está siendo preparada.</span>
                  <% when "listo_para_retirar" %>
                    <span class="user-name">Acercate a el Baratísimo para retirar tu compra</span>
                  <% when "enviado" %>
                    <span class="user-name">¡Tu compra ya está en camino!</span>
                  <% when "entregado" %>
                    <span class="user-name">¡Gracias por tu compra!</span>
                  <% when "cancelado" %>
                    <span class="user-name">Tu compra ha sido cancelada.</span>
                  <% else %>
                    <span class="user-name">No hay un estado disponible para tu compra.</span>
                <% end %>



              </div>

              <%= link_to ecommerce_order_path(order), class: "order-link" do %>
                <span class="order-details-link">Ver compra</span>
              <% end %>

            </div>
            <div class="order-item-detail">
              <span><%= number_to_currency(order.total_price) %></span>
              <span><%= order.payment_method&.name %> - <%= order.shipping_method&.name %></span>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="no-orders-message">No tienes órdenes registradas.</p>
    <% end %>
  </div>
  </div>
</div>

<%= paginate @orders, theme: 'custom-pagination-orders' %>
<%= render 'shared/whatsApp' %>
<%= render 'shared/footer' %>

app/views/ecommerce/orders/shipping_info.html.erb
<% content_for :title, "Información de envío | Baratísimo Bazar" %>

<%= render 'ecommerce/orders/navbar' %>

<div class="order-details-container-shipping">
  <div class="order-container">
    <div class="order-container-primero">
      <div class="products-navigation">
        <ol>
          <li>
            <span class="informacion-primero">1- Información de envío</span>
            <svg class="icon">
              <use xlink:href="<%= asset_path('icons/ecommerce.svg#chevron') %>"></use>
            </svg>
          </li>
          <li>
            <span class="envio-segundo">2- Método de envío</span>
            <svg class="icon">
              <use xlink:href="<%= asset_path('icons/ecommerce.svg#chevron') %>"></use>
            </svg>
          </li>
          <li>
            <span class="pago">3- Medio de pago</span>
          </li>
        </ol>
      </div>

      <div class="order-products">

        <div class="categories-title">
          <div class="title">
            <%= link_to ecommerce_cart_path, class: 'arrow-back-link' do %>
              <svg class="icon">
                <use xlink:href="<%= asset_path('icons/admin.svg#icon-arrow') %>"></use>
              </svg>
            <% end %>
            <h1 class="category-title">Información de envío</h1>
          </div>
        </div>

        <div class="order-products-header">
          <h3 class="order-products-title">Información de envío</h3>
          <% if @addresses.any? %>
            <%= link_to account_addresses_path, class: "btn btn-secondary" do %>
              <span>Agregar nuevos domicilios o editar</span>
              <svg class="icon">
                <use xlink:href="<%= asset_path('icons/admin.svg#arrow-right') %>"></use>
              </svg>

            <% end %>
          <% end %>
        </div>

        <%= form_with model: @order, url: update_shipping_info_ecommerce_order_path(@order), method: :patch, local: true, class: "shipping-info-form" do |f| %>
          <% if @addresses.any? %>
            <% @addresses.each do |address| %>
              <label for="address_<%= address.id %>" class="order-item">
                <%= f.radio_button :address_id, address.id, id: "address_#{address.id}", checked: (@order.address_id == address.id) %>
                <div class="address-card">
                  <span class="title-direccion"><%= address.street_name %> <%= address.street_number %></span>
                  <span class="full-direccion">Cp <%= address.postal_code %> - <%= address.city %> - <%= address.locality %></span>
                  <span class="full-name"><%= current_user.first_name %> <%= current_user.last_name %> - <%= current_user.document_id %></span>
                </div>
              </label>
            <% end %>
          <% else %>
            <div class="order-item">
              <div class="address-card">
                <%= link_to "Agrega una Dirección", new_account_address_path, class: "btn btn-secondary" %>
              </div>
            </div>
          <% end %>

          <div class="actions">
            <%= f.submit "Continuar", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="order-container-segundo">
      <div class="order-summary">
        <h1 class="order-summary-title">Resumen de la compra</h1>
        <div class="barra-separadora"></div>

        <div class="order-summary-details">
          <% if @order.discount_percentage.to_f.positive? %>
            <div class="summary-item">
              <span class="summary-label">Productos (<%= @order.order_items.sum(:quantity) %>)</span>
              <span class="summary-value"><%= number_to_currency(@order.subtotal) %></span>
            </div>
            <div class="summary-item">
              <span class="summary-label">Descuento por cantidad</span>
              <span class="summary-value discount">-<%= @order.discount_percentage.to_i %>%</span>
            </div>
            <div class="barra-separadora"></div>
          <% end %>

          <div class="summary-item">
            <span class="summary-label">Subtotal</span>
            <span class="summary-value"><%= number_to_currency(@order.subtotal_with_discount) %></span>
          </div>
          <div class="summary-item">
            <span class="summary-label">Envío</span>
            <span class="summary-value"><%= number_to_currency(@order.shipping_cost) %></span>
          </div>

          <div class="barra-separadora"></div>
          <div class="summary-item total">
            <span class="summary-label">Total</span>
            <span class="summary-value"><%= number_to_currency(@order.total_price) %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>