config/routes.rb
Rails.application.routes.draw do



  # Home Principal ---------------------------
  namespace :main, path: '' do
    root to: 'home#index'
    get 'nosotros', to: 'static_pages#about', as: :about
    get 'contacto', to: 'static_pages#contact', as: :contact
  end


  post 'mercado_pago/webhook', to: 'mercado_pago_webhooks#receive'

  # E-commerce Principal -------------------------------------------------------------------------
  namespace :ecommerce, path: '' do

    # Ruta para búsqueda de productos
    get 'productos/search', to: 'products#search', as: :search_products


    # Vistas especiales
    get 'super-ofertas', to: 'products#super_offers', as: :super_offers
    get 'novedades',      to: 'products#new_arrivals', as: :new_arrivals
    get 'mas-vendidos',   to: 'products#best_sellers', as: :best_sellers
    get 'historial',      to: 'products#history', as: :history
    delete 'historial',   to: 'products#clear_history', as: :clear_history
    delete 'historial/:id', to: 'products#remove_from_history', as: :remove_from_history


    resources :categories, only: [:index, :show], path: 'categorias' do
      resources :subcategories, only: [:index, :show], path: 'subcategorias' do
        resources :products, only: [:index, :show], path: 'productos'
      end
    end

    resources :products, only: [:index, :show], path: 'productos' do
      resources :product_variants, only: [:show]
    end

    resource :cart, only: [:show], path: 'carrito' do
      delete 'vaciar', to: 'carts#clear_cart', as: :clear_cart
    end

    resources :cart_items, only: [:create, :update, :destroy], path: 'carrito/items'

    resources :orders, only: [:new, :show, :index], path: 'compras' do
      member do
        # Nuevo paso: Selección o creación de dirección de envío
        get   'informacion-envio',  to: 'orders#shipping_info',       as: :shipping_info
        patch 'informacion-envio',  to: 'orders#update_shipping_info',  as: :update_shipping_info

        # Selección del método de envío
        get   'envio',  to: 'orders#shipping',        as: :shipping
        patch 'envio',  to: 'orders#update_shipping', as: :update_shipping

        # Selección del método de pago
        get   'pago',  to: 'orders#payment',         as: :payment
        patch 'pago',  to: 'orders#update_payment',  as: :update_payment

        # Resumen de la compra
        get 'resumen', to: 'orders#summary',         as: :summary

        # Finalización de la compra
        post 'finalizar', to: 'orders#finalize',     as: :finalize

        # Cancelar la compra
        post :cancel

        # Generar PDF de la orden
        get :pdf

        # Confirmación exitosa de la compra
        get 'exito', to: 'orders#success', as: :success

        # Subir comprobante de pago
        patch :upload_comprobante
      end

    end

  end






  # modulo de administración
  namespace :admin do
    root to: 'dashboard#index'
    resources :banners
    resources :discount_ranges, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :shipping_methods, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :payment_methods, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :bank_accounts, only: [:index, :new, :create, :edit, :update, :destroy]
    resource :settings, only: [:show, :update]
    resources :mercado_pago_tokens, only: [:index, :new, :create, :edit, :update, :destroy]

    resources :products do
      get 'load_subcategories', on: :collection
      resources :product_variants, only: [:new, :create, :edit, :update, :destroy]
    end

    resources :categories do
      resources :subcategories, only: [:index, :new, :create, :edit, :update, :destroy]
    end



    resources :orders, only: [:index, :show, :destroy, :update] do
      collection do
        get 'home', to: 'orders#home'
        get 'pendientes', to: 'orders#pendientes'
        get 'pagos', to: 'orders#pagos'
        get 'preparacion', to: 'orders#preparacion'
        get 'finalizadas', to: 'orders#finalizadas'
      end
      member do
        patch 'cambiar_estado', to: 'orders#cambiar_estado'
        get 'print', to: 'orders#print'  # Nueva ruta para impresión
      end
    end

    resources :users do
      collection do
        get 'clientes', to: 'users#clientes'
        get 'admins', to: 'users#admins'
      end
      resources :addresses, only: [:create, :edit, :update, :destroy, :new]
    end

    namespace :users, path: 'usuarios' do
      get '/', to: 'main#index', as: :main
      resources :administradores, only: [:index, :show, :edit, :new, :create, :update, :destroy] do
        member do
          patch :toggle_status
        end
      end
      resources :repositores, only: [:index, :show, :edit, :new, :create, :update, :destroy]
      resources :cajeros, only: [:index, :show, :edit, :new, :create, :update, :destroy]
      resources :clientes_regular, only: [:index, :show, :edit, :new, :create, :update, :destroy]
      resources :clientes_mayorista, only: [:index, :show, :edit, :new, :create, :update, :destroy]
    end

  end

  # Módulo de minoristas
  namespace :store do
    root to: 'home#index'
  end

  # Módulo de mayoristas
  namespace :business do
    # Página principal y estáticas
    root to: 'home#index'

    # Búsqueda y vistas especiales de productos
    get 'productos/search', to: 'products#search', as: :search_products
    get 'super-ofertas', to: 'products#super_offers', as: :super_offers
    get 'novedades', to: 'products#new_arrivals', as: :new_arrivals
    get 'mas-vendidos', to: 'products#best_sellers', as: :best_sellers
    get 'historial', to: 'products#history', as: :history
    delete 'historial', to: 'products#clear_history', as: :clear_history
    delete 'historial/:id', to: 'products#remove_from_history', as: :remove_from_history

    # Navegación por categorías
    resources :categories, only: [:index, :show], path: 'categorias' do
      resources :subcategories, only: [:index, :show], path: 'subcategorias' do
        resources :products, only: [:index, :show], path: 'productos'
      end
    end

    # Productos y variantes
    resources :products, only: [:index, :show], path: 'productos' do
      resources :product_variants, only: [:show]
    end

    # Carrito
    resource :cart, only: [:show], path: 'carrito' do
      delete 'vaciar', to: 'carts#clear_cart', as: :clear_cart
    end

    resources :cart_items, only: [:create, :update, :destroy], path: 'carrito/items'

    # Órdenes
    resources :orders, only: [:new, :show, :index], path: 'compras' do
      member do
        get 'informacion-envio', to: 'orders#shipping_info', as: :shipping_info
        patch 'informacion-envio', to: 'orders#update_shipping_info', as: :update_shipping_info

        get 'envio', to: 'orders#shipping', as: :shipping
        patch 'envio', to: 'orders#update_shipping', as: :update_shipping

        get 'pago', to: 'orders#payment', as: :payment
        patch 'pago', to: 'orders#update_payment', as: :update_payment

        get 'resumen', to: 'orders#summary', as: :summary
        post 'finalizar', to: 'orders#finalize', as: :finalize
        post :cancel
        get :pdf
        get 'exito', to: 'orders#success', as: :success
        patch :upload_comprobante
      end
    end

    # Cuenta del usuario
    namespace :account, path: 'mi-cuenta' do
      get '/', to: 'main#show', as: :main

      resource :profile, only: [:show, :update], path: 'perfil' do
        get 'informacion', on: :collection
        get 'editar-nombre', to: 'profiles#edit_name', as: :edit_name
        get 'editar-telefono', to: 'profiles#edit_phone', as: :edit_phone
        get 'editar-dni', to: 'profiles#edit_dni', as: :edit_dni
        patch 'foto', to: 'profiles#update_profile_picture', as: :update_picture

        get 'verificacion-fiscal', to: 'profiles#fiscal_verification_form', as: :fiscal_verification_form
        patch 'constancia-fiscal', to: 'profiles#upload_constancia_fiscal', as: :upload_constancia_fiscal
        get 'verificacion-en-proceso', to: 'profiles#fiscal_verification_pending', as: :fiscal_verification_pending
      end

      resources :lists, only: [:index, :show, :new, :create, :destroy], path: 'listas' do
        resources :list_items, only: [:create, :destroy], path: 'productos'
      end

      resources :addresses, only: [:index, :new, :create, :edit, :update, :destroy, :show], path: 'direcciones' do
        member do
          patch :set_default
        end
      end

      resources :transporte_preferidos, only: [:index, :new, :create, :edit, :update, :destroy], path: 'transportes-preferidos' do
        member do
          patch :set_default
        end
      end


      resources :orders, only: [:index, :show], path: 'compras'
      resource :facturacion, only: [:show], path: 'facturacion'


      resource :settings, only: [:show], path: 'configuracion' do
        delete 'eliminar-cuenta', on: :collection, to: 'settings#delete_account', as: :delete_account

        get 'editar-contrasena', to: 'settings#edit_password', as: :edit_password
        patch 'actualizar-contrasena', to: 'settings#update_password', as: :update_password

        get 'editar-email', to: 'settings#edit_email', as: :edit_email
        patch 'actualizar-email', to: 'settings#update_email', as: :update_email
      end

    end

    # Centro de ayuda
    namespace :help, path: 'ayuda' do
      get '/', to: 'static_pages#index', as: :index
      get 'nosotros', to: 'static_pages#about', as: :about
      get 'contacto', to: 'static_pages#contact', as: :contact
      get 'constancia-arca', to: 'static_pages#constancia_arca', as: :constancia_arca
      # Más artículos en el futuro:
      # get 'como-comprar', to: 'static_pages#how_to_buy', as: :how_to_buy
    end



  end

  # Módulo de punto de venta (POS)
  namespace :pos do
    root to: 'home#index'
  end

  # Módulo de logística
  namespace :logistics do
    root to: 'home#index'
  end

app/controllers/account/accounts_controller.rb
class Account::AccountsController < ApplicationController
  before_action :authenticate_user!

  def main
    @user = current_user
  end
end

app/controllers/account/addresses_controller.rb
class Account::AddressesController < ApplicationController
  before_action :authenticate_user!

  def index
    @addresses = current_user.addresses.order(created_at: :desc)
  end

  def show
    @address = current_user.addresses.find(params[:id])
  end


  def new
    @address = current_user.addresses.new
  end

  def create
    @address = current_user.addresses.new(address_params)
    if @address.save
      redirect_to account_addresses_path, notice: 'Dirección agregada con éxito.'
    else
      render :new
    end
  end

  def edit
    @address = current_user.addresses.find(params[:id])
  end

  def update
    @address = current_user.addresses.find(params[:id])
    if @address.update(address_params)
      redirect_to account_addresses_path, notice: 'Dirección actualizada con éxito.'
    else
      render :edit
    end
  end

  def destroy
    @address = current_user.addresses.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to account_addresses_path, notice: 'Dirección eliminada con éxito.' }
      format.turbo_stream
    end
  end

  private

  def address_params
    params.require(:address).permit(
      :street_name,
      :street_number,
      :floor,
      :apartment,
      :locality,
      :city,
      :province_code,
      :postal_code,
      :indications
    )
  end

end

app/controllers/account/profiles_controller.rb
class Account::ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :update, :update_profile_picture]

  def show
    # Vista del perfil del usuario
  end

  def information
    # Vista de información personal
  end

  def edit_name
    # Formulario para editar nombre
  end

  def edit_email
    # Formulario para editar email
  end

  def edit_phone
    # Formulario para editar teléfono
  end

  def edit_dni
    @user = current_user
  end


  def update
    if @user.update(user_params)
      redirect_to information_account_profiles_path(@user), notice: 'Perfil actualizado exitosamente.'
    else
      flash.now[:alert] = 'Hubo un problema al actualizar el perfil.'
      render :edit_name  # Renderiza la vista de edición con errores
    end
  end

  def update_profile_picture
    if params[:user][:profile_picture].present?
      processed_image = ImageProcessing::MiniMagick
                          .source(params[:user][:profile_picture])
                          .resize_to_limit(600, 600)
                          .convert("webp")
                          .call

      @user.profile_picture.purge if @user.profile_picture.attached?
      @user.profile_picture.attach(
        io: processed_image,
        filename: "profile_picture_#{@user.id}.webp",
        content_type: "image/webp"
      )

      redirect_to account_profile_path(@user), notice: 'Foto de perfil actualizada exitosamente.'
    else
      redirect_to account_profile_path(@user), alert: "Debés seleccionar una imagen."
    end
  end


  private

  def set_user
    @user = current_user
  end

  def profile_picture_params
    params.require(:user).permit(:profile_picture)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone, :document_type, :document_id)
  end

end

app/controllers/account/settings_controller.rb
class Account::SettingsController < ApplicationController
  before_action :authenticate_user!

  def show
    # Vista de ajustes
  end

  def delete_account
    # current_user.purchases.destroy_all    # Elimina todas las compras del usuario
    current_user.destroy
    redirect_to root_path, notice: 'Tu cuenta ha sido eliminada.'
  end
end

app/controllers/admin/addresses_controller.rb
class Admin::AddressesController < ApplicationController
  before_action :set_user
  before_action :authenticate_user!
  before_action :set_address, only: [:edit, :update, :destroy]

  def new
    @address = @user.addresses.new
  end

  def create
    @address = @user.addresses.new(address_params)
    if @address.save
      redirect_to [:admin, @user], notice: 'Dirección agregada exitosamente.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to [:admin, @user], notice: 'Dirección actualizada.'

    else
      render :edit
    end
  end

  def destroy
    @address = @user.addresses.find(params[:id])
    @address.destroy
    redirect_to admin_user_path(@user), notice: 'Dirección eliminada exitosamente.'
  end


  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_address
    @address = @user.addresses.find(params[:id])
  end

  def address_params
    params.require(:address).permit(:street_name, :street_number, :postal_code, :city, :locality, :floor, :apartment, :indications)
  end
end

app/controllers/business/account/addresses_controller.rb
module Business
  module Account
    class AddressesController < ApplicationController
      before_action :set_envio_address, only: [:edit, :update, :destroy]

      def index
        @envio_addresses = current_user.addresses.direccion_envio.order(created_at: :desc)
      end

      def new
        @envio_address = current_user.addresses.new(address_type: :direccion_envio)
      end

      def create
        @envio_address = current_user.addresses.new(address_params)
        @envio_address.address_type = :direccion_envio

        # Si no se marcó como default y no hay ninguna dirección predeterminada aún
        if !@envio_address.default_shipping && current_user.addresses.where(default_shipping: true).empty?
          @envio_address.default_shipping = true
        end

        if @envio_address.save
          redirect_to business_account_addresses_path, notice: 'Dirección creada correctamente.'
        else
          render :new, status: :unprocessable_entity
        end
      end

      def edit
      end

      def set_default
        current_user.addresses.update_all(default_shipping: false)
        address = current_user.addresses.find(params[:id])
        address.update(default_shipping: true)
        redirect_to business_account_addresses_path, notice: "Dirección principal actualizada."
      end

      def update
        if @envio_address.update(address_params)
          redirect_to business_account_addresses_path, notice: 'Dirección actualizada correctamente.'
        else
          render :edit, status: :unprocessable_entity
        end
      end

      def destroy
        was_default = @envio_address.default_shipping
        @envio_address.destroy

        if was_default
          next_default = current_user.addresses.order(created_at: :asc).first
          next_default.update(default_shipping: true) if next_default.present?
        end

        redirect_to business_account_addresses_path, notice: 'Dirección eliminada correctamente.'
      end

      private

      def set_envio_address
        @envio_address = current_user.addresses.direccion_envio.find(params[:id])
      end

      def address_params
        params.require(:address).permit(
          :street_name,
          :street_number,
          :floor,
          :apartment,
          :locality,
          :city,
          :province_code,
          :postal_code,
          :indications,
          :default_shipping
        )
      end
    end
  end
end

app/controllers/business/account/main_controller.rb
# app/controllers/business/account/main_controller.rb
module Business
  module Account
    class MainController < ApplicationController
      def show
      end
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/business/account/addresses/edit.html.erb
<% content_for :title, "Edita tus datos personales" %>

<div class="account-business-adresses-new">
  <div class="container-edit-profile">

    <div class="products-navigation">
      <ol>
        <li>
          <%= link_to business_account_profile_path do %>
            <span>Mi perfil</span>
            <svg class="icon">
              <use xlink:href="<%= asset_path('icons/business.svg#flecha-separacion-siguiente') %>"></use>
            </svg>
          <% end %>
        </li>

        <li>
          <%= link_to business_account_addresses_path do %>
            <span>Mis direcciones</span>
            <svg class="icon">
              <use xlink:href="<%= asset_path('icons/business.svg#flecha-separacion-siguiente') %>"></use>
            </svg>
          <% end %>
        </li>

        <li>
          <span>Editar mi domicilio</span>
        </li>

      </ol>
    </div>

    <div class="profile-header">
      <h1 class="profile-title">¿Querés cambiar algo de tu domicilio?</h1>
      <p class="profile-description">Modificá los datos que necesites y guardá los cambios.</p>
      <p class="profile-instructions">Recordá que esta dirección será usada para tus próximos envíos.</p>
    </div>

    <div class="profile-form">
      <%= form_with model: [:business, :account, @envio_address], local: true do |form| %>
        <div class="form-group">
          <div class="form-label-wrapper">
            <%= form.text_field :street_name, class: 'form-input', placeholder: 'Calle' %>
            <%= form.label :street_name, 'Calle', class: 'form-label' %>
          </div>
          <% if @envio_address.errors[:street_name].any? %>
            <div class="error-message"><%= @envio_address.errors[:street_name].first %></div>
          <% end %>
        </div>

        <div class="form-grid">
          <div class="form-group">
            <div class="form-label-wrapper">
              <%= form.number_field :street_number, class: 'form-input', placeholder: 'Número' %>
              <%= form.label :street_number, 'Número', class: 'form-label' %>
            </div>
            <% if @envio_address.errors[:street_number].any? %>
              <div class="error-message"><%= @envio_address.errors[:street_number].first %></div>
            <% end %>
          </div>

          <div class="form-group">
            <div class="form-label-wrapper">
              <%= form.number_field :postal_code, class: 'form-input', placeholder: 'Código Postal' %>
              <%= form.label :postal_code, 'Código Postal', class: 'form-label' %>
            </div>
            <% if @envio_address.errors[:postal_code].any? %>
              <div class="error-message"><%= @envio_address.errors[:postal_code].first %></div>
            <% end %>
          </div>

          <div class="form-group">
            <div class="form-label-wrapper">
              <%= form.text_field :locality, class: 'form-input', placeholder: 'Provincia' %>
              <%= form.label :locality, 'Provincia', class: 'form-label' %>
            </div>
            <% if @envio_address.errors[:locality].any? %>
              <div class="error-message"><%= @envio_address.errors[:locality].first %></div>
            <% end %>
          </div>

          <div class="form-group">
            <div class="form-label-wrapper">
              <%= form.text_field :city, class: 'form-input', placeholder: 'Ciudad' %>
              <%= form.label :city, 'Ciudad', class: 'form-label' %>
            </div>
            <% if @envio_address.errors[:city].any? %>
              <div class="error-message"><%= @envio_address.errors[:city].first %></div>
            <% end %>
          </div>

          <div class="form-group">
            <div class="form-label-wrapper">
              <%= form.text_field :apartment, class: 'form-input', placeholder: 'Departamento (opcional)' %>
              <%= form.label :apartment, 'Departamento (opcional)', class: 'form-label' %>
            </div>
          </div>

          <div class="form-group">
            <div class="form-label-wrapper">
              <%= form.text_field :floor, class: 'form-input', placeholder: 'Piso (opcional)' %>
              <%= form.label :floor, 'Piso (opcional)', class: 'form-label' %>
            </div>
          </div>
        </div>

        <div class="form-group text-area">
          <div class="form-label-wrapper">
            <%= form.text_area :indications, class: 'form-input', placeholder: 'Indicaciones para la entrega (opcional)' %>
            <%= form.label :indications, 'Indicaciones para la entrega (opcional)', class: 'form-label' %>
          </div>
        </div>

        <div class="space">
          <%= link_to 'Volver', business_account_addresses_path, class: 'btn btn-secondary' %>
          <%= form.submit 'Guardar Dirección', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/business/account/addresses/index.html.erb
<% content_for :title, "Mis direcciones | Baratísimo Bazar" %>


<div class="account-business-adresses">
  <section class="sidebar-accounts-business">
    <div class="sidebar-section">

      <%= link_to business_account_main_path, class: 'link' do %>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-home-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Mi cuenta</h2>
      <% end %>

      <%= link_to business_account_orders_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-compras-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Compras</h2>
      <% end %>

      <%= link_to business_account_profile_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-user-account-2') %>"></use>
        </svg>
        <h2 class="select-view">Mi perfil</h2>
      <% end %>

      <%= link_to business_account_lists_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-listas-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Mis listas</h2>
      <% end %>

      <%= link_to business_account_facturacion_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-facturacion-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Facturación</h2>
      <% end %>

      <%= link_to business_account_settings_path, class: 'link' do %>
        <div class="barra-active"></div>
        <svg class="icon">
          <use xlink:href="<%= asset_path('icons/business.svg#icon-ajustes-account-1') %>"></use>
        </svg>
        <h2 class="title-view">Ajustes</h2>
      <% end %>

    </div>
  </section>

  <section class="account-business-content">
    <div class="profile-info-business">
      <div class="profile-info-container">


        <div class="products-navigation">
          <ol>
            <li>
              <%= link_to business_account_profile_path do %>
                <span>Mi perfil</span>
                <svg class="icon">
                  <use xlink:href="<%= asset_path('icons/business.svg#flecha-separacion-siguiente') %>"></use>
                </svg>
              <% end %>
            </li>

            <li>
              <span>Mis direcciones</span>
            </li>

          </ol>
        </div>

        <div class="categories-title">
          <div class="title">
            <%= link_to business_account_profile_path, class: 'arrow-back-link' do %>
              <svg class="icon">
                <use xlink:href="<%= asset_path('icons/business.svg#icon-arrow') %>"></use>
              </svg>
            <% end %>
            <h1 class="category-title">Administrá tus domicilios</h1>
          </div>
        </div>

        <div class="card-user-container">
          <% if @envio_addresses.any? %>
            <% @envio_addresses.each do |address| %>
                <div class="card-address">
                  <div class="card-adresses-info">
                    <div class="icon-container">
                      <svg class="icon">
                        <use xlink:href="<%= asset_path('icons/business.svg#casa-icono') %>"></use>
                      </svg>
                    </div>
                    <div class="user-info">
                      <div class="name-direccion-container">
                        <p class="name-direccion"><%= address.street_name %> <%= address.street_number %></p>
                        <% if address.default_shipping %>
                          <span class="badge badge-primary">Predeterminado</span>
                        <% end %>
                      </div>
                      <p class="full-direccion">Código postal <%= address.postal_code %> - <%= address.locality %> - <%= address.city %></p>
                      <p class="name-user"><%= address.user.first_name %> <%= address.user.last_name %> - <%= address.user.phone %></p>
                    </div>
                    <div class="filter-container-modal-menu" data-controller="menu">
                      <div class="filter">
                        <%= button_tag type: 'button', class: 'filter-button', data: { action: "click->menu#open" } do %>
                          <svg class="icon">
                            <use xlink:href="<%= asset_path('icons/business.svg#menu-icon-adreses') %>"></use>
                          </svg>
                        <% end %>
                      </div>

                      <!-- Modal -->

                      <div class="modal-background" data-menu-target="background" data-action="click->menu#close"></div>
                      <div class="modal-lateral" data-menu-target="modal">
                        <div class="modal-lateral-content">

                          <div class="modal-lateral-header">
                            <button class="close-modal" data-action="click->menu#close">
                              <svg class="icon">
                                <use xlink:href="<%= asset_path('icons/business.svg#icon-custom-menu-close') %>"></use>
                              </svg>
                            </button>
                          </div>

                          <div class="modal-lateral-body">
                            <div class="modal">

                              <% unless address.default_shipping %>
                                <%= button_to set_default_business_account_address_path(address), method: :patch, class: 'btn-info btn-detalle' do %>
                                  <svg class="icon">
                                    <use xlink:href="<%= asset_path('icons/business.svg#Icon-adresess-1') %>"></use>
                                  </svg>
                                  <span class="ms-2">Establecer como predeterminado</span>
                                <% end %>
                              <% end %>

                              <%= link_to edit_business_account_address_path(address), class: "btn-info btn-detalle" do %>
                                <svg class="icon">
                                  <use xlink:href="<%= asset_path('icons/business.svg#icon-perfil-user') %>"></use>
                                </svg>
                                <span>Editar</span>
                              <% end %>

                              <% if current_user.orders.where(address: address).empty? %>
                                <%= button_to business_account_address_path(address), method: :delete, data: { confirm: '¿Estás seguro?' }, class: 'btn-info btn-detalle' do %>
                                  <svg class="icon">
                                    <use xlink:href="<%= asset_path('icons/business.svg#icon-cancelar') %>"></use>
                                  </svg>
                                  <span class="ms-2">Eliminar</span>
                                <% end %>
                              <% else %>
                                <div class="btn-info btn-detalle disabled">
                                  <svg class="icon">
                                    <use xlink:href="<%= asset_path('icons/business.svg#icon-cancelar') %>"></use>
                                  </svg>
                                  <span class="ms-2">Eliminar</span>
                                </div>
                              <% end %>
                            </div>
                          </div>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>


            <% end %>
          <% end %>

          <%= link_to new_business_account_address_path, class: "add-new-adresess" do %>
            <span>Agregar domicilio</span>
          <% end %>
        </div>

      </div>
    </div>
  </section>

</div>

<%= render 'business/shared/footer_business' %>